### PR TITLE
(Deno) stuff

### PR DESCRIPTION
**Pull request by liimee**
- you can test deno stuff in a deno playground somewhere in the internet.
- eval==eval

### CODE REVIEW

**Review by Electogenius — CHANGES_REQUESTED** [review]
I actually didn’t add a separate file for deno because I was too lazy to change both files when I changed something in the code, that’s why I added that weird file fetch thing

Do you think a `try{export default EGCode}catch(e){}` at the end would work?

edit: also thankssss aaaaa

**Comment by liimee** [comment]
I think there's a thing.. UMD stuff or uh.. hold a sec

**Comment by liimee** [comment]
hold a sec, I think I know something

**Comment by liimee** [comment]
I don't know, maybe that'll work, I'll test

**Comment by liimee** [comment]
if you want, the user must set the type to "module" like `<script type="module" src="thing.js"></script>`?

**Comment by liimee** [comment]
ouch
Screenshot from 2021-05-08 06-54-54
___
do you want to just bundle it like [this](https://deno.land/manual@v1.9.2/tools/bundler)? the user must set the type to "module" though
___
also if you're lazy to edit two files I tested a GitHub Actions thingy that kinda works lol (it runs when you push an edit to the first file)

**Comment by liimee** [comment]
ouch
Screenshot from 2021-05-08 06-54-54
___
~~do you want to just bundle it like [this](https://deno.land/manual@v1.9.2/tools/bundler)? the user must set the type to "module" though~~
___
also if you're lazy to edit two files I made a GitHub Actions thingy that (surprisingly) works lol (it runs when you push an edit to the first file)

lmk if you wanna use it :) (you probably won't lol)

**Comment by Electogenius** [comment]
Maybe, I still need to spend an hour understanding how bundling works because brain === microscopic
> also if you're lazy to edit two files I made a GitHub Actions thingy that (obviously) works lol (it runs when you push an edit to the first file)

woahhh

I’ll ask you if I want to use it, if what I’m going to try works

**Comment by liimee** [comment]
> Maybe, I still need to spend an hour understanding how bundling works because brain

I tried bundling and basically the result is same lol

so yeah I guess we either use 2 files or 1 file but you need to do `type="module"`(?)

wait what no it's not "obviously works"

**Comment by Electogenius** [comment]
> I tried bundling and basically the result is same lol

oh, ok

I added a file called compiler.bundle.js with the same code + export default egcode, I’ll try it out
> wait what no it's not "obviously works"

pfft no it is

Edit: module works with browser.

**Comment by liimee** [comment]
ok so I guess just close this? (you may need to update the help.md)

**Comment by Electogenius** [comment]
Okay

Also thanksssssssssss again aa

also:
- Deno also works ✅ 
- Nodejs says import can only be used in a module but other websites say it can be used anywhere so idk

**Comment by liimee** [comment]
> * Nodejs says import can only be used in a module but other websites say it can be used anywhere so idk

I think you need Babel to use import, never tried so not really sure

you can do `module.exports` or something like that in basic node

**Comment by Electogenius** [comment]
I _was_ thinking of using if(module!==undefined){module.exports=EGCode}, but I scrolled further in the website I was using as a reference and it had a section on import/export so uh

I’ll try the module.exports thing :shipit:

**Comment by liimee** [comment]
> I _was_ thinking of using if(module!==undefined){module.exports=EGCode}, but I scrolled further in the website I was using as a reference and it had a section on import/export so uh

(afaik) many libraries uses something similar like that to check if the library is used on a browser

I think to make it easy just use webpack/rollup/something like that
if you want I can try to do it :)

**Comment by Electogenius** [comment]
> (afaik) many libraries uses something similar like that to check if the library is used on a browser

Oh, cool

> I think to make it easy just use webpack/rollup/something like that
if you want I can try to do it :)

Oh, I don't know what that idea but I'll see :)

**Comment by liimee** [comment]
just did a quick rollup ([output](https://gist.github.com/liimee/a4b6e2230acf30af16079ed84731c826)), tested with browser and node, works perfectly. (you also don't need to set the type to module)

**Comment by Electogenius** [comment]
Woahhh thanks so much

I’ll just uh copy paste commit push eeeeeeeee

**Comment by liimee** [comment]
(it doesn't work on deno though)

**Comment by Electogenius** [comment]
Ooff
I’ll try testing my if module != undefined thing again maybe

edit: well obviously same error

so I guess I can just give up on nodejs lol, not much of a problem 🤷‍♂️ 
I’ll revert to the export default

**Comment by liimee** [comment]
but node.js is more popular 🤷‍♂️

**Comment by Electogenius** [comment]
I know, but I, annoyingly, care more about the web than terminals

also idk how to implement it in all platforms without messing stuff up so uh yeah

(I might possibly make EGCode in python too but idk if I can handle indentation and a lack of {})

**Comment by liimee** [comment]
uh ok then

**Pull request closed without merging**
